name: "reactions"
services:
  reactions-postgres:
    container_name: reactions-postgres
    image: postgres:17.5-alpine
    restart: always
    environment:
      PGDATA: /pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/pgdata
    ports:
      - "5432:5432"

  reactions-minio:
    image: quay.io/minio/minio:RELEASE.2025-02-28T09-55-16Z-cpuv1
    container_name: reactions-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin 
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000" 
      - "9001:9001" 
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ./var/storage/postgres_data
      o: bind

  minio_data:
    driver: local
    driver_opts:
      type: none
      device: ./var/storage/minio_data
      o: bind
