name: Deploy frontend to prod

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/deploy_frontend.yml
      - docker/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push bot image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/images/frontend/Dockerfile
          push: true
          tags: |
            registry.gitlab.com/ayomits/fear-helper:reaction_frontend_latest
            registry.gitlab.com/ayomits/fear-helper:reaction_frontend
          build-args:
            APP_ENV=prod
          no-cache: true
          
      - name: Trigger Dokploy Deployment
        run: |
          curl -X 'POST' \
          'https://dokploy.uppy-bot.ru/api/trpc/application.deploy' \
          -H 'accept: application/json' \
          -H "x-api-key: ${{ secrets.DOKPLOY_TOKEN }}" \
          -H 'Content-Type: application/json' \
          -d '{
              "json":{
                  "applicationId": "9WBYK4I0lamGS7vN2Afho"
              }
          }'